"""Tests for the IO module."""

from pathlib import Path

import numpy as np
import pytest

from numcompute.io import load_data


def test_load_data_reads_numeric_csv_and_skips_header(tmp_path: Path) -> None:

	csv_file = tmp_path / "numeric_data.csv"
	csv_file.write_text(
		"col1,col2,col3\n"
		"1,2,3\n"
		"4,,6\n"
		"7,8,9\n",
		encoding="utf-8",
	)

	result = load_data(str(csv_file), skip_header=1)

	expected = np.array(
		[
			[1.0, 2.0, 3.0],
			[4.0, np.nan, 6.0],
			[7.0, 8.0, 9.0],
		]
	)

	assert isinstance(result, np.ndarray)
	np.testing.assert_array_equal(result, expected)


def test_load_data_raises_file_not_found_error_for_missing_file(tmp_path: Path) -> None:
	"""load_data should fail fast when the CSV path does not exist."""

	missing_file = tmp_path / "does_not_exist.csv"

	with pytest.raises(FileNotFoundError, match=r"file not found"):
		load_data(str(missing_file))


def test_load_data_supports_custom_delimiter(tmp_path: Path) -> None:
	csv_file = tmp_path / "tab_data.tsv"
	csv_file.write_text("1\t2\t3\n4\t5\t6\n", encoding="utf-8")

	result = load_data(str(csv_file), delimiter="\t")

	np.testing.assert_array_equal(result, np.array([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]]))


def test_load_data_skip_header_zero_reads_all_rows(tmp_path: Path) -> None:
	csv_file = tmp_path / "no_header.csv"
	csv_file.write_text("1,2\n3,4\n5,6\n", encoding="utf-8")

	result = load_data(str(csv_file))

	assert result.shape == (3, 2)
	np.testing.assert_array_equal(result, np.array([[1.0, 2.0], [3.0, 4.0], [5.0, 6.0]]))


def test_load_data_skip_multiple_header_rows(tmp_path: Path) -> None:
	csv_file = tmp_path / "multi_header.csv"
	csv_file.write_text(
		"# generated by something\n"
		"# units: meters\n"
		"x,y\n"
		"1,2\n"
		"3,4\n",
		encoding="utf-8",
	)

	result = load_data(str(csv_file), skip_header=3)

	np.testing.assert_array_equal(result, np.array([[1.0, 2.0], [3.0, 4.0]]))


def test_load_data_treats_missing_fields_as_nan(tmp_path: Path) -> None:
	"""All-missing fields in a row should become NaN, not zeros."""
	csv_file = tmp_path / "with_missing.csv"
	csv_file.write_text(",,\n1,2,3\n", encoding="utf-8")

	result = load_data(str(csv_file))

	assert np.isnan(result[0]).all()
	np.testing.assert_array_equal(result[1], np.array([1.0, 2.0, 3.0]))


def test_load_data_returns_1d_array_for_single_column(tmp_path: Path) -> None:
	csv_file = tmp_path / "single_col.csv"
	csv_file.write_text("1\n2\n3\n4\n", encoding="utf-8")

	result = load_data(str(csv_file))

	# np.genfromtxt returns 1-D for a single column.
	assert result.shape == (4,)
	np.testing.assert_array_equal(result, np.array([1.0, 2.0, 3.0, 4.0]))


def test_load_data_handles_empty_data_file(tmp_path: Path) -> None:
	"""A file with only a header and no data rows should not crash."""
	csv_file = tmp_path / "header_only.csv"
	csv_file.write_text("a,b,c\n", encoding="utf-8")

	with pytest.warns(UserWarning, match="Empty input file"):
		result = load_data(str(csv_file), skip_header=1)

	assert isinstance(result, np.ndarray)
	assert result.size == 0
